[package]
name = "r-pi"
version = "0.1.0"
authors = ["Jiewen Yao <jiewen.yao@intel.com>"]
edition = "2018"

categories = [
        "embedded",
        "hardware-support",
        "no-std",
]
description = "UEFI PlatformInitialization (PI) Reference Specification Protocol Constants and Definitions"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
